import { Roboto } from '@next/font/google'
import Head from 'next/head'
import { Frontpage } from '../components/Frontpage'

// @TODO
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Just Countdown</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Frontpage />
		</>
	)
}
